version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing cfn-lint and taskcat
      - pip install cfn-lint
      - pip install taskcat
      - echo "taskcat version:"
      - taskcat --version

  build:
    commands:
      - echo Running cfn-lint to validate CloudFormation template
      - cfn-lint Group25.yaml

      - echo Running Taskcat to test CloudFormation template
      - taskcat test run --debug > taskcat_output.log || echo Taskcat failed

      - echo Contents of taskcat_output.log
      - cat taskcat_output.log  # Xem nội dung của taskcat_output.log
      - ls -l  # Liệt kê các tệp trong thư mục hiện tại

artifacts:
  files:
    - Group25.yaml
    - taskcat_output.log  # Đẩy tệp log lên cùng với artifacts
  discard-paths: yes
  base-directory: .  # Thư mục cơ bản chứa các tệp
